### ISSUE TITLE
packages to be installed

### ISSUE THREAD

**Issue by SeonjeongHwang** [searchableai/ChainCQG#2]
Hi,

Thanks for your great research and source codes!
Could you share the list of packages and their version to run the code?

**Comment by g-jing** [comment]
@SeonjeongHwang Thanks for your interest!
The package used in this project are pretty common such as "transformers". We will also list the packages in the repo later.

**Comment by ahmednasserswe** [comment]
@g-jing which version of Torchfly is used in the project?

**Comment by gouqi666** [comment]
@ahmednasserswe  hello, I also want to know more about Torchfly, I find that it just have one version in https://pypi.org/project/TorchFly/#history , have you solved that problem 'No module named 'torchfly.training.arguments' ?
