### ISSUE TITLE
preprocessing input file

### ISSUE THREAD

**Issue by SeonjeongHwang** [searchableai/ChainCQG#3]
Hi,

I tried running the code, but I found that "train_coqa_two_gpt.pkl" file is needed.
And I couldn't find the preprocessing codes to transform the original coqa-train.json file to the CQG form.
Can you share the preprocessing codes?

**Comment by g-jing** [comment]
This is the trained model file. You should first use the training script to get it.

**Comment by SeonjeongHwang** [comment]
Thank you so much for the quick reply.
However, when I executed the training script "run_generation_coqa_chaincqg.sh", I get the following error.

`Traceback (most recent call last):
  File "main_coqa_two_gpt.py", line 80, in <module>
    train_data = torch.load(train_dataset_dir)
  File "/home/seonjeong/anaconda3/envs/chain/lib/python3.6/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/seonjeong/anaconda3/envs/chain/lib/python3.6/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/seonjeong/anaconda3/envs/chain/lib/python3.6/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '../data/coqa/train_coqa.pkl'`

I thought that I need pkl files as input dataset according to the function "get_dataset_dir_by_name" in utils.py, 

`    elif dataset_name == "coqa":
        train_dataset_dir = "data/coqa/train_coqa.pkl"
        val_dataset_dir = "data/coqa/dev_coqa.pkl"
        test_dataset_dir = "data/coqa/test_coqa.pkl"`

And I couldn't find the code for preprocessing the original coqa dataset to CQG form in "main_coqa_two_gpt.py"
